title: A whimsical screenname
description: Some Random thoughts / findings / knowledge bases from an experienced Cloud Engineer
baseurl:
url: https://sam-gordon-f.github.io # the base hostname AND PROTOCOL for your site, e.g. http://example.com
github_url: https://github.com/sam-gordon-f/sam-gordon-f.github.io
github_url_raw: https://github.com/sam-gordon-f/sam-gordon-f.github.io/tree/master/
permalink: /:categories/:title

content_type: Knowledge Base #Define whether this is a knowledge base, help center, or something else
use_authors: true #Set this to false to disable showing post authors

brand_logo: logo.png
brand_name:
header: A Whimsical Screename
header_formatted: "<span class = \"spanA\">A.</span> <span class = \"spanW\">Whimsical.</span> <span class = \"spanS\">Screename.</span>"
subheader: A collection of posts / knowledge articles

meta_image: odin-meta.png

# Social Links
twitter_username: samgord42226167
facebook_page: https://www.facebook.com/ahectic
github_username: sam-gordon-f
email: sam.gordon.f@gmail.com
full_name: Sam Gordon
linkedin_page: https://www.linkedin.com/in/sam-gordon-10b42985/
instagram_username:

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

sass:
  sass_dir:          _scss
  style:            :compressed

paginate: 3

markdown: kramdown
highlighter: rouge
